config/routes.rb
Sharedearthapp::Application.routes.draw do
  resources :transparency, :only => [:index] do
    collection do
      put 'accept_tr'
    end
  end

  resource :password_resets 

  match "/password_reset/:id/edit" => "password_resets#edit"
  match "/password_reset/:id/update" => "password_resets#update"

  ActiveAdmin.routes(self)

  resources :fb_friends, :only => [:index]
  get 'connect'     => "fb_friends#index"
  get 'findtheothers' => "fb_friends#index"
  get 'search_fb_friends' => "fb_friends#search_fb_friends"
  get 'search_people'     => "fb_friends#search_people"

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  resources :terms, :only => [:index] do
    collection do
      put 'accept_tc'
      put 'accept_pp'
      get 'principles'
    end
  end

  resources :legal_notices, :only => [:index] do
    collection do
      put 'accept_legal_notice'
      put 'accept_pp'
      get 'principles'
    end
  end

   resources :requested_invitations, :only => [:create]

  resources :comments, :only => [:create]

  resources :invitations, :except => [:destroy, :edit, :show, :new]

  get "invitations/validate"
  get "invitations/purge"
  get "invitations/preview"
  get "invitations/switch"
  get "invitations/invite"

  get "people/cancel/:id" => "people#cancel"

  get "search/index"

  resources :items do
    member do
      put "mark_as_normal"
      put "mark_as_lost"
      put "mark_as_damaged"
      put "mark_as_hidden"
      put "mark_as_unhidden"
      post "share_mine"
      post "share_mine_type"
    end
  end

  resources :people, :only => [:new, :show, :edit, :update, :index, :destroy] do
    member do
      get :confirm_email_changing
      get :please_confirm_email_changing
      get :network
      get :my_network
    end
  end

  resources :network_requests, :only => [:create, :destroy] do
    member do
      put "confirm"
      put "deny", :action => :destroy
    end
  end

  resources :human_network, :only => [ :destroy ]

  resources :item_requests, :except => [:index, :destroy, :edit], :path => "requests", :as => "requests" do
    member do
      put "accept"
      put "reject"
      put "complete"
      put "cancel"
      put "collected"
      put "recall"
      put "return"
      put "acknowledge"
      put "cancel_recall"
      put "cancel_return"
      put "returned"
      post 'new_comment'
    end
    resources :feedbacks
  end

  resources :villages do
    member do
      put 'join'
      put 'leave'
    end
  end
  resources :entities, :only => [:destroy] do
    collection do
      get 'grow'
    end
  end

  resources :users do
    member do
      get :confirm
      post :resent_activation
      get :please_activate_email
    end
  end

  resources :sessions, :only => [:new, :create]

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  match "/dashboard", :to => "pages#dashboard"
  match "/community", :to => "pages#community"
  match "/principles", :to => "terms#principles"
  match '/about' => 'pages#about'
  match '/contribute' => 'pages#contribute'
  match '/no_javascript' => 'pages#no_javascript'
  match '/collect_email' => 'pages#collect_email'

  match "/common", :to => "pages#commons"

  post "/create_trusted_network", :to => "human_network#create_trusted_networks"

  root :to => "pages#index"

  match '*a', :to => 'application#missing_route'   #Catch wrong route problem
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  default_scope :order => 'created_at ASC'

  validates_length_of :comment, :maximum => 420
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
  model_name = params[:comment][:commentable_type]
  record_commentable = model_name.constantize.find(params[:comment][:commentable_id])
  @comment = record_commentable.comments.create(:commentable => record_commentable, :user_id => current_user.id, :comment => params[:comment][:comment] )

  record_commentable.leave_comment!(current_person) if model_name == "ItemRequest"
  
  respond_to do |format|
      format.html { redirection_rules(model_name, record_commentable) }
      format.json do
        @comment_html = render_to_string( :partial => 'comments/comment.html.erb', :locals => {:c => @comment } )
        render :json => { :success => true, :comment_html => @comment_html  }
      end
  end
 end
 
 private
 def redirection_rules(model_name, record_commentable)
   case model_name
    when "ItemRequest"
      redirect_to request_path(record_commentable)
    when "Item"
      redirect_to item_path(record_commentable)
    when "EventLog"
      redirect_to dashboard_path
    else
     #  
  end
 end
end

app/controllers/fb_friends_controller.rb
require 'fb_service'

class FbFriendsController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :check_facebook_session, :only => [:index, :search_fb_friends]

  def index
    if !(fb_user = current_person.facebook_user)
      return redirect_to :dashboard, :warning => "Facebook not connected"
    end
    
    @people  = ((FbService.get_my_friends(fb_user.token).order(:name) +  current_person.suggested_people).uniq) - current_person.trusted_friends
    @people = @people - [Person.find(current_user.id)]
    @villages = current_person.suggested_villages

    #@trusted_network_count = current_person.trusted_network.count
    #@people_in_community_count =  current_person.people_in_community_count

  end

  def search_fb_friends
    fb_user = current_person.facebook_user
    if !fb_user
      return redirect_to :dashboard, :warning => "Facebook not connected"
    else
      search_terms = params[:search_terms] || ''
      @people = FbService.search_fb_friends(fb_user.token, search_terms)
      raise NotActivated if @people.nil?
      render :index
    end
  end

  def search_people
    @searching_people = true
    search_terms = params[:search_terms] || ''

    @people = Person.search(search_terms)
    @people = @people - [current_user.person] unless @people.empty?

    render :index
  end

  private
  
  def check_facebook_session
   user = FbGraph::User.new(:access_token => current_user.token)
   user.fetch
  end
end

app/helpers/fb_friends_helper.rb
module FbFriendsHelper

  def trust_action_link_for(person)
    if person.requested_trusted_relationship?(current_person)
      text = "cancel trust request"
      href = network_request_path(person.requested_trusted_relationship(current_person))
      options = { :method => :delete }

    elsif current_person.trusts?(person)
      text = "withdraw trust"
      href = human_network_path(current_person.trusts?(person))
      options = { :method => :delete }

    elsif current_person.requested_trusted_relationship?(person)
      text = "confirm trust"
      # href = confirm_human_network_request_path(
      #        current_person.requested_trusted_relationship(person))
      options = { :method => :put, :id => 'confirm_button' }

    else
      text = "trust"
      href = network_requests_path(:trusted_person_id => person) 
      options = { :method => :post }
    end
    
    options[:remote] = true

    link_to(text, href, options)
  end

  def get_count_trusted_network_person_ids (person, village)
    HumanNetwork.trusted_network_person_ids_count(person, village)
  end

  def get_count_people_from_community(person, village)
    HumanNetwork.people_from_community_count(person, village)
  end

  def get_count_people_live_in(village)
    HumanNetwork.village_members(village).count
  end

  def get_count_entity_items(village)
     ResourceNetwork.group_items(village).count
  end
  
end

app/views/comments/fb_friends/index.html.haml
!!! 5
%html
	%head
		%title= @page_title
	%body 
		%div.wrapper
			%section.container.connect-search.subheader
				%h1 Connect
				%div.row
					=render "search_box"
					%div.buttons.right
						=link_to "Create Village", new_village_path, :class => "button create-village", :onclick => "overlay()"

		%div.wrapper
			%div.container
				%section.page-content.clearfix
					%div.suggestions
						%div.row.suggest
							%h1.communities-block Suggested Communities
							=link_to "Refresh", "#", :class => "refresh-button"
						%div.community-box
							%div.single-community
								-unless @villages.nil?
									%ul
										-for village in @villages
											%li
												%div.content
													%h1 
														=village.name
													%span.meta
														="#{village.street} #{village.state} #{village.country}"
													=link_to "Join", join_village_path(village), :method => :put, :class => "button ui-switch" unless village.is_member_or_admin?(current_person)
													=link_to "Leave", leave_village_path(village), :method => :put if village.is_member?(current_person)
					
					%div.suggestions
						%div.row.suggest
							%h1.people-block People I May Know
							=link_to "Refresh", "#", :class => "refresh-button" 
							
						%div.community-box
							%div.single-community
								/ %img{:src=>"/assets/img/picture.png", :alt=>""}
								%div.content
									-if @people.empty?
										= params[:search_terms] ? 'Search term not found' : 'Enter search term'
									-else
										%span.meta
											= render 'people_list', :people => @people
									
				%aside.dashboard-sidebar.sidebar
					%div.block.sidebar-block
						%hgroup
							%h1.suggest-side-header musicians in the inner west
						%div.block-list
							%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\
						%ul.block-list
							%li
								%div.trusted-block
									%strong 15 people
									from your trusted network
							%li
								%div.communities-block
									%strong 15 people
									from your trusted network
							%li
								%div.people-block
									%strong 350 people
									in this group
							%li
								%div.items-block 
									%strong 15 people
									from your trusted network
						%a{:href=>"#", :title=>"View more", :class=>"more"} View More