config/routes.rb
Sharedearthapp::Application.routes.draw do
  resources :transparency, :only => [:index] do
    collection do
      put 'accept_tr'
    end
  end

  resource :password_resets 

  match "/password_reset/:id/edit" => "password_resets#edit"
  match "/password_reset/:id/update" => "password_resets#update"

  ActiveAdmin.routes(self)

  resources :fb_friends, :only => [:index]
  get 'connect'     => "fb_friends#index"
  get 'findtheothers' => "fb_friends#index"
  get 'search_fb_friends' => "fb_friends#search_fb_friends"
  get 'search_people'     => "fb_friends#search_people"

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  resources :terms, :only => [:index] do
    collection do
      put 'accept_tc'
      put 'accept_pp'
      get 'principles'
    end
  end

  resources :legal_notices, :only => [:index] do
    collection do
      put 'accept_legal_notice'
      put 'accept_pp'
      get 'principles'
    end
  end

   resources :requested_invitations, :only => [:create]

  resources :comments, :only => [:create]

  resources :invitations, :except => [:destroy, :edit, :show, :new]

  get "invitations/validate"
  get "invitations/purge"
  get "invitations/preview"
  get "invitations/switch"
  get "invitations/invite"

  get "people/cancel/:id" => "people#cancel"

  get "search/index"

  resources :items do
    member do
      put "mark_as_normal"
      put "mark_as_lost"
      put "mark_as_damaged"
      put "mark_as_hidden"
      put "mark_as_unhidden"
      post "share_mine"
      post "share_mine_type"
    end
  end

  resources :people, :only => [:new, :show, :edit, :update, :index, :destroy] do
    member do
      get :confirm_email_changing
      get :please_confirm_email_changing
      get :network
      get :my_network
    end
  end

  resources :network_requests, :only => [:create, :destroy] do
    member do
      put "confirm"
      put "deny", :action => :destroy
    end
  end

  resources :human_network, :only => [ :destroy ]

  resources :item_requests, :except => [:index, :destroy, :edit], :path => "requests", :as => "requests" do
    member do
      put "accept"
      put "reject"
      put "complete"
      put "cancel"
      put "collected"
      put "recall"
      put "return"
      put "acknowledge"
      put "cancel_recall"
      put "cancel_return"
      put "returned"
      post 'new_comment'
    end
    resources :feedbacks
  end

  resources :villages do
    member do
      put 'join'
      put 'leave'
    end
  end
  resources :entities, :only => [:destroy] do
    collection do
      get 'grow'
    end
  end

  resources :users do
    member do
      get :confirm
      post :resent_activation
      get :please_activate_email
    end
  end

  resources :sessions, :only => [:new, :create]

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  match "/dashboard", :to => "pages#dashboard"
  match "/community", :to => "pages#community"
  match "/principles", :to => "terms#principles"
  match '/about' => 'pages#about'
  match '/contribute' => 'pages#contribute'
  match '/no_javascript' => 'pages#no_javascript'
  match '/collect_email' => 'pages#collect_email'

  match "/common", :to => "pages#commons"

  post "/create_trusted_network", :to => "human_network#create_trusted_networks"

  root :to => "pages#index"

  match '*a', :to => 'application#missing_route'   #Catch wrong route problem
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!, :except => :confirm_email_changing
  before_filter :get_person, :except => [:index, :confirm_email_changing]
  before_filter :only_if_person_is_signed_in!, :only => [:edit, :update]
  before_filter :only_own_network!, :only => [:my_network]

  def confirm_email_changing
    @person = Person.find(params[:id])
    if @person.verify_email_change!(params[:code])
      session[:user_id] || @person.user.first.id
      redirect_to edit_person_path(@person), :notice => I18n.t('messages.people.email_changed')
    else
      redirect_to :root, :warning => I18n.t('messages.people.change_email_wrong')
    end
  end

  def please_confirm_email_changing
    if params[:resend]
      @person.send_email_changing_confirmation
      redirect_to please_confirm_email_changing_person_path(@person), :notice => "Message sent"
    end
  end

  def index
    @people = current_user.person.trusted_friends

    respond_to do |format|
      format.html { render :action => 'search' if params[:search] }
      format.xml  { render :xml => @people }
    end
  end

  def show
    @events = @person.network_activity.page(params[:page]).per_page(5)
    if @person.belongs_to? current_user
      if params[:filter_type].nil?
        @items = @person.items.without_deleted.sort_by{|i| i.item_type.downcase}
      else
        @items = @person.items.without_deleted.with_type(params[:filter_type])
      end
      @unanswered_requests = @person.unanswered_requests
    else
      if params[:filter_type].nil?
        @items = @person.items.without_deleted.visible_to_other_users.without_hidden.sort_by{|i| i.item_type.downcase}
      else
        @items = @person.items.without_deleted.visible_to_other_users.without_hidden.with_type(params[:filter_type])
      end
      @unanswered_requests = @person.unanswered_requests(current_user.person)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  def network
    @other, @mutual_friends, @trusted_network, @extended_network = [], [], [], []
    current_person = current_user.person
    @self = ( current_person.id == @person.id )
    unless params[:type].nil?
      case params[:type]
          when 'mutual'
            @mutual_friends = @person.mutural_friends(current_user.person)
          when 'extended'
            #
          when 'other'
            mutual_friends = @person.mutural_friends(current_user.person)
            trusted_network = @person.trusted_friends
            facebook_friends = @person.facebook_friends
            @other = facebook_friends + trusted_network - mutual_friends
            @other.delete_at(@other.index(current_person) || @other.length) unless @person.belongs_to? current_user
          else
            #
      end
    else
      @trusted_network = @person.trusted_friends
      @mutual_friends = @person.mutural_friends(current_user.person)
      facebook_friends = @person.facebook_friends
      @other = facebook_friends + @trusted_network - @mutual_friends
      @other.delete_at(@other.index(current_person) || @other.length) unless @person.belongs_to? current_user
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # Filter view network items and activity based on entity type, action is deprecated will be removed

  def my_network
    case params[:type]
      when 'trusted'
        @items = @person.trusted_friends_items(params[:filter_type]).sort_by{|i| i.item_type.downcase}
        @events = current_user.trusted_network_activity.page(params[:page]).per_page(25)
      else
        @items = @person.personal_network_items(params[:filter_type]).sort_by{|i| i.item_type.downcase}
        @events = current_user.network_activity.page(params[:page]).per_page(25)
    end
  end

  def edit
    @person.update_attributes(:has_reviewed_profile => true)
  end

  def update
    redirect_path = @person.has_reviewed_profile? ? person_path(@person) : root_path
    @person.update_attributes(:has_reviewed_profile => true)

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html do
          if @person.waiting_for_new_email_confirmation?
            redirect_to please_confirm_email_changing_person_path(@person)
          else
            redirect_to redirect_path
          end
        end
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  def cancel
    redirect_path = @person.has_reviewed_profile? ? person_path(@person) : root_path
    @person.update_attributes(:has_reviewed_profile => true)
    redirect_to redirect_path
  end

  private

  def get_person
    @person = Person.find_by_id(params[:id])
    if @person.nil? || (current_user.person != @person && @person.authorised_account == false)
      redirect_to dashboard_path
    end
  end

  def only_if_person_is_signed_in!
    redirect_to(root_path, :alert => I18n.t('messages.you_cannot_edit_others')) and return unless current_user.person == @person
  end

  def only_own_network!
    redirect_to(root_path, :alert => I18n.t('messages.people.only_own_network')) and return unless current_user.person == @person
  end
end

app/helpers/people_helper.rb
module PeopleHelper
 def mutual_friends
   params[:type] == 'mutual'
 end
 
 def all_friends
   params[:type] == 'all'
 end
 
 def other_friends
   params[:type] == 'other'
 end
 
 def extended_friends
   params[:type] == 'extended'
 end
 
 def trusted_network
   params[:type] == 'trusted'
 end
 
 def in_network?(current_person, other_person )
   	if current_person.trusts?(other_person)
		link = link_to 'In your trusted network', (network_person_path(other_person))
	else	
		if other_person.requested_trusted_relationship?(current_person)
			 link = "Trust request pending"
		else
		   link = link_to 'Not in your trusted network', (network_person_path(other_person)) 
		end
	end
		# "#{image}<p>#{link}</p>".html_safe
 end
 
 def trusted_person_class(person)
	if current_user.person.trusts?(person)
		" trusted"
	else
		" untrusted"
	end
 end

end

app/views/people/_new_person.html.haml
%li
	.inner-content
		%p
			%span Welcome to sharedearth.net
			%br
			Get started by adding your items via the share button above.

app/views/people/_person.html.haml
%li
	=image_tag person.avatar(:square), :class => "thumb"
	%div
		%p
			= link_to_person person 

app/views/people/edit.html.haml
#item-profile-form-page
	.profile-form-page
		#content
			.content-box-holder.no-bg
				%ul
					%li
						%section.avatar-and-social-connection
							= image_tag @person.avatar(:large), :class => "thumb", :alt => @person.name
							-if connections = @person.users.from_networks.presence 
								="Linked Accounts: #{connections.map(&:network_title).join(", ")}"

							-if @person.users.where(:provider => "facebook").empty?
								=link_to "Connect with Facebook", "/auth/facebook"

							-if @person.users.where(:provider => "google_oauth2").empty?
								= link_to "Connect with Google", "/auth/google_oauth2"

						.inner-content.rhs
							%h2 Edit Profile

							= form_for(@person, :html => { :multipart => true }) do |f|
								= render :partial => "shared/error_messages", :locals => { :model => @person }

								%ul
									%li
										= f.label "Your Name"
										= f.text_field :name

									%li
										= f.label "Email"
										= f.text_field :new_email, :value => @person.new_email.presence || @person.email

										-if @person.new_email.present?
											%small
												="Need confirmation, old email: #{@person.email}"

									%li
										= f.label "Location"
										= f.text_field :location, {:class=>"text-input", :maxlength=>"50"}

									%li
										= f.label "About me" 
										= f.text_area :description, {:class=>"text-input", :rows=>"5", :maxlength=>"400"}

									%li.checkbox-holder
										= f.label 'Enable smart email notifications'
										= f.check_box :smart_notifications

									%li.clearfix
										.actions
											%ul
												%li
													=f.submit :value => "Save"
												%li
													=link_to 'cancel', { :controller => "people", :action => "cancel",:id => @person.id }

		#sidebar
			= render :partial => "shared/trust_profile", :locals => { :person => @person, :name => false }
			= render :partial => "shared/latest_activity_person", :locals => { :person => @person }

app/views/people/edit.js.erb
window.location = "/";

app/views/people/index.html.haml
%h1 My friends

%table
	%tr
		%th	Name
		%th	

-@people.each do |person|
	%tr
		%td 
			= link_to person.name, person_path(person)

-end if !@people.nil?

app/views/people/my_network.html.haml
#community-page.clearfix
	#sidebar-left
		-if params[:type].nil?
			= image_tag("your_network.png", :class => "thumb", :alt => "Your Network")

		-elsif trusted_network
			= image_tag("trusted_icon_yourself.png", :class => "thumb", :alt => "Trusted Network")

		%ul
			%li.all
				= link_to 'Your Network', my_network_person_path(current_user.person)
			%li.trusted
				= link_to 'Trusted Network', my_network_person_path(current_user.person, :type => 'trusted')


	#content
		.content-box-holder.no-bg
			%ul
				%li.content-box.clearfix
					.inner-content
						%h2
							-if params[:type].nil? 
								Your Network 
							-elsif trusted_network
								Trusted Network

						%p.description
							-if params[:type].nil?
								The people from your trusted network, communities and villages.
								=link_to "Find the others", connect_path, :class => "trusted"
							-elsif trusted_network
								The family, friends and people you trust unreservedly, and share willingly with.
								%br
								=link_to "Find the others", connect_path, :class => "trusted"

			= render "items/item_list"

	#sidebar
		-title = trusted_network ? 'Trusted Network Activity' : 'Your Network Activity'
		= render :partial => "shared/news_feed_person", :locals => { :events => @events, :title => title

app/views/people/network.html.haml
#user-trusted-page
	#sidebar-left
		= image_tag @person.avatar(:medium), :class => "thumb"
		%ul

			%li.all
				= link_to 'All', network_person_path(@person)

			-unless @self

				%li= link_to 'Mutual', network_person_path(@person, :type => 'mutual')

				%li= link_to 'Others', network_person_path(@person, :type => 'other')

	#content
		.content-box-holder
			= "#{@person.name} Network"

			-unless @self
				%ul
					%li{:class => "clearfix"}
						= in_network?(current_user.person, @person )

			-if !@mutual_friends.empty?

				.network-holder.clearfix
					.lhs
						%ul
							-@mutual_friends.each do |p|
								%li
									= image_tag p.avatar(:square), :class => "thumb"
								%p
									= link_to p.name, person_path(p), :class => trusted_person_class(p)

					.rhs.clearfix
						= image_tag(!@self ? "ic-trusted-net-others-green-large.png" : "ic-trusted-net-you-green.png", :class => "icons", :alt => "Trusted Profile")

						%h4
							= !@self ? "mutual networks" : "trusted network"

						%p
							%a{:href => "#"}
								= trusted_network = @person.mutural_friends_count(current_user.person)

							= (trusted_network == 1) ? " person " : " people "
							in your #{!@self ? "mutual" : "trusted"} network

							

			-elsif mutual_friends
				%h3 This user has no mutual friends with you


			-if !@other.empty?
				.network-holder

					.lhs
						%ul
							-@other.each do |p|
								%li
									= image_tag p.avatar(:square), :class => "thumb"
								%p
									= link_to p.name, person_path(p)

					.rhs.clearfix
						= image_tag("ic-others-large.png", :class => "icons", :alt => "Others")
						%h4 Others
						%p
							%a{:href => "#"}
								= other_count = @other.count

							= (other_count == 1) ? " other " : " others "

			-elsif other_friends
				%h3 This user has no other friends in network


			-if params[:type].nil? && !@self

				%ul
					%li.clearfix
						= image_tag("ic-trusted-network.png", :class => "icons", :alt => "Trusted Network")

					
					%a{:href => "#"}
						= trusts_me = @person.trusts_me_count
						=(trusts_me == 1) ? "person in their trusted network" : "people in their trusted network" 
						

app/views/people/please_confirm_email_changing.haml
.single-page
  %h2 Confirm your new email address

  %p
    We've sent a confirmation message to <strong>#{@person.new_email}</strong>. Please open then message and follow link to continue.

  %p
    If you do not receive the message in next 10 minutes #{link_to "click link", please_confirm_email_changing_person_path(@person, :resend => true)} to resend. 

app/views/people/search.html.haml
#search-page.clearfix
	= render :partial => "shared/search_sidebar"

	#content
		.content-box-holder.no-bg
			.search-holder
				= form_tag items_path, :method => 'get' do
					%div
						= text_field_tag :search, params[:search]
						%button{:type => "submit", :title => "search"} Search
			%h2
				= link_to image_tag('ic-person.png', :alt => "People", :title => "People")
				People in 
				= link_to image_tag('ic-village-comm.png', :alt => "Village", :title => "Village")
				Sydney

			.items-list.clearfix
				-if @people.empty?
					Sorry, nothing matches your search criteria
				%h3.default-title
					Frome your trusted network

				%ul.clearfix
					-@people.each do |person|
						%li.item.clearer
							%a{:href => "/items/1"}
  								%img.thumb{:alt => "", :src => "http://graph.facebook.com/100002086303869/picture/"}
  							%div
  								%p
  									= link_to person.name, person_path(person)
  					-end if !@people.nil?

app/views/people/show.html.haml
!!! 5
%html
	%head
		%title= @page_title
		
		/ %link{:type=>"text/css", :href=>"less/profile.less", :rel=>"stylesheet/less"}

		/ %script{:type=>"text/javascript", :src=>"js/modernizr.js"}
		/ %script{:type=>"text/javascript", :src=>"js/less.js"}
		/ %script{:type=>"text/javascript", :src=>"js/jquery.js"}
		/ %script{:type=>"text/javascript", :src=>"js/jquery.ui.1.9.1.js"}

		/ %script{:type=>"text/javascript", :src=>"js/jquery.rating.js"}
		/ %script{:type=>"text/javascript", :src=>"js/jquery.screwdefaultbuttonsV2.min.js"}
		/ %script{:type=>"text/javascript", :src=>"js/functions.js"}
		
		/ %script{:type=>"text/javascript", :src=>"js/modal.js"}
	%body 
		
		%div.wrapper
			%div.container
				%section.community-feed.page-content.clearfix
					%section.community-page-header.clearfix
						%div.community-avatar
							= image_tag @person.avatar(:large), :class => "square", :alt => @person.name
						%div.community-content
							%h1 
								="#{@person.name}'s Reputation"
							%h2 A human being from planet earth
							%p 
								=@person.description	
						%hr.row
						%form.row
							%textarea Post to community discussion board
					%div.feed#tabs
						%ul.feed-tabs
							%li
								%a{:href=>"#tabs-1", :title=>"",:id=>""}>< My Activity		
							%li
								%a{:href=>"#tabs-2", :title=>"", :class=>"active",  :id=>""}>< Resources
							%li
								%a{:href=>"#tabs-3", :title=>"", :id=>""}>< Asks
						%div.feed-content.activity#tabs-1
							= render :partial => "shared/latest_activity_person", :locals => { :person => @person } 
							
						%div.feed-content.resources#tabs-2
							%div.third
								%ul
									%li
										%a{:href=>"#"} Lorem ipsum
									
							%div.third
								%ul
									%li
										%a{:href=>"#"} Lorem ipsum
									
							%div.third
								%ul
									%li
										%a{:href=>"#"} Lorem ipsum
									%li
										%a{:href=>"#"} Lorem ipsum
									
				%aside.dashboard-sidebar.sidebar
					%div.block.sidebar-block.reputation

						%header.user-header
							%div.user-avatar
								= image_tag @person.avatar(:large), :class => "square", :alt => @person.name
							%div.user-info
								%div.name 
									/ Kryptonite D-lock
								%div.location 
									= @person.location
						%hr
						%h1 reputation
						%ul.block-list.reputation-list
							=render :partial => "shared/reputation_profile", :locals => { :person => @person, :name => false }

					%div.block.sidebar-block.trust-status
						%div.heading
							%h1 trust profile
							%span.status.trusted
								=render :partial => "shared/trust_status", :locals => { :person => @person, :name => false}

						%ul.block-list.trust-list
							= render :partial => "shared/trust_profile", :locals => { :person => @person, :name => false}

					=render :partial => "shared/community_sidebar"