config/routes.rb
Sharedearthapp::Application.routes.draw do
  resources :transparency, :only => [:index] do
    collection do
      put 'accept_tr'
    end
  end

  resource :password_resets 

  match "/password_reset/:id/edit" => "password_resets#edit"
  match "/password_reset/:id/update" => "password_resets#update"

  ActiveAdmin.routes(self)

  resources :fb_friends, :only => [:index]
  get 'connect'     => "fb_friends#index"
  get 'findtheothers' => "fb_friends#index"
  get 'search_fb_friends' => "fb_friends#search_fb_friends"
  get 'search_people'     => "fb_friends#search_people"

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  resources :terms, :only => [:index] do
    collection do
      put 'accept_tc'
      put 'accept_pp'
      get 'principles'
    end
  end

  resources :legal_notices, :only => [:index] do
    collection do
      put 'accept_legal_notice'
      put 'accept_pp'
      get 'principles'
    end
  end

   resources :requested_invitations, :only => [:create]

  resources :comments, :only => [:create]

  resources :invitations, :except => [:destroy, :edit, :show, :new]

  get "invitations/validate"
  get "invitations/purge"
  get "invitations/preview"
  get "invitations/switch"
  get "invitations/invite"

  get "people/cancel/:id" => "people#cancel"

  get "search/index"

  resources :items do
    member do
      put "mark_as_normal"
      put "mark_as_lost"
      put "mark_as_damaged"
      put "mark_as_hidden"
      put "mark_as_unhidden"
      post "share_mine"
      post "share_mine_type"
    end
  end

  resources :people, :only => [:new, :show, :edit, :update, :index, :destroy] do
    member do
      get :confirm_email_changing
      get :please_confirm_email_changing
      get :network
      get :my_network
    end
  end

  resources :network_requests, :only => [:create, :destroy] do
    member do
      put "confirm"
      put "deny", :action => :destroy
    end
  end

  resources :human_network, :only => [ :destroy ]

  resources :item_requests, :except => [:index, :destroy, :edit], :path => "requests", :as => "requests" do
    member do
      put "accept"
      put "reject"
      put "complete"
      put "cancel"
      put "collected"
      put "recall"
      put "return"
      put "acknowledge"
      put "cancel_recall"
      put "cancel_return"
      put "returned"
      post 'new_comment'
    end
    resources :feedbacks
  end

  resources :villages do
    member do
      put 'join'
      put 'leave'
    end
  end
  resources :entities, :only => [:destroy] do
    collection do
      get 'grow'
    end
  end

  resources :users do
    member do
      get :confirm
      post :resent_activation
      get :please_activate_email
    end
  end

  resources :sessions, :only => [:new, :create]

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  match "/dashboard", :to => "pages#dashboard"
  match "/community", :to => "pages#community"
  match "/principles", :to => "terms#principles"
  match '/about' => 'pages#about'
  match '/contribute' => 'pages#contribute'
  match '/no_javascript' => 'pages#no_javascript'
  match '/collect_email' => 'pages#collect_email'

  match "/common", :to => "pages#commons"

  post "/create_trusted_network", :to => "human_network#create_trusted_networks"

  root :to => "pages#index"

  match '*a', :to => 'application#missing_route'   #Catch wrong route problem
end

app/views/shared/_commons_sidebar.html.haml
%div.block.sidebar-block1
	%hgroup
		%h1 building the commons
		%h2 Do you own the following?
	%ul.block-list
		-for i in 0..7
			%li
				%span.resource
					= truncate @houses[i].item_type , :length => 15
				= link_to "Share Mine", share_mine_type_item_path(@houses[i].item_type), :id =>"#{@houses[i].item_type}", :class => "button", :remote=>true, :method=>:post

	%a{:href=>"common", :title=>"View more", :class=>"more"} view more

app/views/shared/_event_log_entry.html.haml
.inner-content
	%p
		= render :partial => "shared/event_log_sentence", :locals => { :event_log => event_log }

	.action.clearfix
		= render :partial => "shared/event_log_actions_compact", :locals => { :event_log => event_log }

app/views/shared/_event_log_sentence.html.haml
/ DISPLAY EVENT LOG SENTANCES

= event_log_sentence(event_log, nil, EventDisplay::DASHBOARD_FEED)

app/views/shared/_footer.html.haml
.footer
  %ul.fl.footer_menu
    %li= link_to "About","/about",:class=>"borderNone"
    %li= link_to "Commons","#"
    %li= link_to "Legal","#"
    %li= link_to "Transparency","/transparency"
    %li= link_to "Blog","#"
    %li= link_to "Contribute","/contribute"
    %li= link_to "Contact","mailto:info@sharedearth.net"
    .clear
  .fr.social_icons
    = link_to (image_tag "tweet.png"),"https://twitter.com/sharedearthnet", :onclick => "window.open(this.href); return false;", :title => "SharedEarth on Facebook",:class=>"fl tweet"
    = link_to (image_tag "fb.png"),"http://www.facebook.com/pages/sharedearthnet/263473190379196?ref=ts", :onclick => "window.open(this.href); return false;", :title => "SharedEarth on Facebook",:class=>"fl tweet"
  .clear

app/views/shared/_item_request_actions_compact.html.erb
<%
	# compact version of available item request actions based on user's role
	# for example used in dashboard.html.erb
%>

<% if [ItemRequest::STATUS_ACCEPTED, ItemRequest::STATUS_COLLECTED, ItemRequest::STATUS_COMPLETED].include? req.status %>
	<li>
		<%= link_to 'view action', request_path(req), :id => "request_#{req.id}" %>
	</li>
<% else %>
	<li>
		<%= link_to 'view request', request_path(req), :id => "request_#{req.id}" %>
	</li>
<% end %>

<% if req.status == ItemRequest::STATUS_REQUESTED %>

	<%= gifter_only(req) do %>
		<li>
			<%= link_to "accept", accept_request_path(req, ActionFormat::FORMAT), :id => "accept_button", :class => "dashboard-action-link", :method => :put %>
		</li>
		<li>
			<%= link_to "reject", reject_request_path(req, ActionFormat::FORMAT), :id => "reject_button", :class => "dashboard-action-link", :method => :put %>
		</li>
		
		
	<% end %>
	
	<%= requester_only(req) do %>
		<li>
			<%= link_to "cancel", cancel_request_path(req, ActionFormat::FORMAT), :id => "cancel_button", :class => "dashboard-action-link", :method => :put %>
		</li>
	<% end %>

<% elsif req.status == ItemRequest::STATUS_ACCEPTED %>

	<%= requester_and_gifter_only(req) do %>
		<% if req.item.purpose == Item::PURPOSE_GIFT || req.item.purpose == Item::PURPOSE_SHAREAGE %>
		<li>	
		  <%= link_to "cancel", cancel_request_path(req, ActionFormat::FORMAT), :id => "cancel_button", :class => "dashboard-action-link", :method => :put %>
		</li>
		<% end %>
		<li>	
			<%= link_to "collected", collected_request_path(req, ActionFormat::FORMAT), :id => "collected_button", :class => "dashboard-action-link", :method => :put %>
		</li>
		<% if req.item.purpose != Item::PURPOSE_GIFT && req.item.purpose != Item::PURPOSE_SHAREAGE  %>
		<li>
			<%= link_to "complete", complete_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
		</li>
  	<% end %>
		
	<% end %>

<% elsif req.status == ItemRequest::STATUS_COLLECTED %>

	<%= requester_and_gifter_only(req) do %>
    <% unless req.item.purpose == Item::PURPOSE_SHAREAGE -%>
		<li>
			<%= link_to "complete", complete_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
		<li>
    <% else -%>
      	<li>
      <% if !req.item.is_owner?(current_person) -%>
   			<%= link_to "return", return_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
      <% else -%>
         <%= link_to "recall", recall_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
      <% end -%>
    		<li>
    <% end %>
	<% end %>

<% elsif req.status == ItemRequest::STATUS_RECALL %>

	<%= requester_and_gifter_only(req) do %>
      	<li>
      <% if !req.item.is_owner?(current_person) -%>
         <%= link_to "acknowledge", acknowledge_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
      <% else -%>
					<%= link_to "cancel recall", cancel_recall_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
      <% end -%>
    		<li>
  <% end %>
<% elsif req.status == ItemRequest::STATUS_RETURN %>

	<%= requester_and_gifter_only(req) do %>
      	<li>
      <% if !req.item.is_owner?(current_person) -%>
					<%= link_to "cancel return", cancel_return_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
      <% else -%>
         <%= link_to "acknowledge", acknowledge_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
      <% end -%>
    		<li>
  <% end %>
<% elsif req.status == ItemRequest::STATUS_ACKNOWLEDGED %>

	<%= requester_and_gifter_only(req) do %>
      	<li>
         <%= link_to "item returned", returned_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put %>
    		<li>
  <% end %>
<% end %>
<% comments = req.comments.count %>
<li class="last"><a href="#" class="action-comments-show-hide">comments(<%= comments ||= 0 %>)</a></li>

app/views/shared/_item_request_actions_compact.html.haml
-if [ItemRequest::STATUS_ACCEPTED, ItemRequest::STATUS_COLLECTED, ItemRequest::STATUS_COMPLETED].include? req.status
	
	= link_to 'view action', request_path(req), :id => "request_#{req.id}"
-else
	
	= link_to 'view request', request_path(req), :id => "request_#{req.id}"

-if req.status == ItemRequest::STATUS_REQUESTED
	= gifter_only(req) do
		%div.story-status
			%div.feedback-buttons 
				= link_to image_tag("thumbs_up.png"), accept_request_path(req, ActionFormat::FORMAT), :id => "accept_button", :class => "like-button", :method => :put
			
				= link_to image_tag("thumbs_down.png"), reject_request_path(req, ActionFormat::FORMAT), :id => "reject_button", :class => "dislike-button", :method => :put
	= requester_only(req) do
		
		= link_to "cancel", cancel_request_path(req, ActionFormat::FORMAT), :id => "cancel_button", :class => "dashboard-action-link", :method => :put

-elsif req.status == ItemRequest::STATUS_ACCEPTED
	= requester_and_gifter_only(req) do

		-if req.item.purpose == Item::PURPOSE_GIFT || req.item.purpose == Item::PURPOSE_SHAREAGE
			
			= link_to "cancel", cancel_request_path(req, ActionFormat::FORMAT), :id => "cancel_button", :class => "dashboard-action-link", :method => :put
		
		= link_to "collected", collected_request_path(req, ActionFormat::FORMAT), :id => "collected_button", :class => "dashboard-action-link", :method => :put

		-if req.item.purpose != Item::PURPOSE_GIFT && req.item.purpose != Item::PURPOSE_SHAREAGE
			
			= link_to "complete", complete_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put

-elsif req.status == ItemRequest::STATUS_COLLECTED
	= requester_and_gifter_only(req) do
		-unless req.item.purpose == Item::PURPOSE_SHAREAGE
			
			= link_to "complete", complete_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put
		-else
			
			-if !req.item.is_owner?(current_person)
				= link_to "return", return_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put
			-else
				= link_to "recall", recall_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put

-elsif req.status == ItemRequest::STATUS_RECALL
	= requester_and_gifter_only(req) do
		
		-if !req.item.is_owner?(current_person)
			= link_to "acknowledge", acknowledge_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put
		-else
			= link_to "cancel recall", cancel_recall_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put

-elsif req.status == ItemRequest::STATUS_RETURN
	= requester_and_gifter_only(req) do
		
		-if !req.item.is_owner?(current_person)
			= link_to "cancel return", cancel_return_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put
		-else
			= link_to "acknowledge", acknowledge_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put

-elsif req.status == ItemRequest::STATUS_ACKNOWLEDGED
	= requester_and_gifter_only(req) do
		
		= link_to "item returned", returned_request_path(req, ActionFormat::FORMAT), :id => "complete_button", :class => "dashboard-action-link", :method => :put

/ -comments = req.comments.count

/ %li{:class => "last"}
/ 	%a.action-comments-show-hide{:href => "#"}
/ 		comments(#{comments ||= 0})

app/views/shared/_item_request_sentence123.html.erb
<% sentence_ending, full_sentence = "", ""%>
<% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
<% gifter = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
<% gifter_non_possessive = link_to_person(req.gifter, :downcase_you => true, :possessive => false, :class => "capitalize positive") %>
<% requester = link_to_person(req.requester, {:class => "positive" }) %>
<% if req.requested? %>
    <% if req.item.share? -%>
			  <% person_one = link_to_person(req.requester, {:class => "positive" }) %>
			  <% sentence = "made a request to borrow" %>
			  <% person_two = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
			  <% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
    <% elsif req.item.is_shareage? -%>
        <% if req.requester?(current_user.person) -%>
            <% join_sentence = req.requester?(current_person) ? "are requesting" : "is requesting"%>
            <% full_sentence = "You " + join_sentence + " " + gifter + " " + item + " for shareage" %>  
        <% else %>
            <% full_sentence = requester + " is requesting " + gifter + " " + item + " for shareage" %> 
        <% end -%>
	  <% else %>
	    <% if req.requester?(current_user.person) -%>
	        <% person_one = link_to_person(req.requester, {:class => "positive" }) %>
			    <% sentence = "requested" %>
			    <% person_two = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
			    <% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
	    <% else -%>
	        <% person_one = link_to_person(req.requester, {:class => "positive" }) %>
			    <% sentence = "has requested" %>
			    <% person_two = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
			    <% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
	    <% end -%>
	  <% end %>
<% elsif req.accepted? %>
  <% if req.item.share? -%>
    <% if req.requester?(current_user.person) %>
		  <% person_one = link_to_person(req.requester, {:class => "positive" }) %>
		  <% sentence = "are sharing" %>
		  <% person_two = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
		  <% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
	  <% else %>
		  <% person_one = link_to_person(req.requester, {:class => "positive" }) %>
		  <% sentence = "is sharing" %>
		  <% person_two = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
		  <% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
	  <% end %>
  <% elsif req.item.is_shareage? -%>
    <% if req.requester?(current_user.person) %>
      <% full_sentence = "Collect " + gifter + " " + item + " for shareage"%>
	  <% else %>
      <% full_sentence = "Awaiting collection of your " + item + " by " + requester %>
	  <% end %>
  <% else %>
    <% if req.requester?(current_user.person) %>
		  <% person_one = link_to_person(req.requester, {:class => "positive" }) %>
		  <% sentence = "have to collect" %>
		  <% person_two = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
		  <% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
	  <% else %>
		  <% person_one = link_to_person(req.requester, {:class => "positive" }) %>
		  <% sentence = "will collect" %>
		  <% person_two = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
		  <% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
	  <% end %>
  <% end %>
<% elsif req.collected? %>
  <% if req.item.is_shareage? -%>
    <% if req.requester?(current_user.person) %>
      <% full_sentence = item + " is now in shareage"%>
	  <% else %>
      <% full_sentence = "Your " + item + " is now in shareage" %>
	  <% end %>
  <% else %>
		  <% person_one = link_to_person(req.requester, {:class => "positive" }) %>
		  <% sentence = "collected" %>
		  <% person_two = link_to_person(req.gifter, :downcase_you => true, :possessive => true, :class => "capitalize positive") %>
		  <% item = link_to req.item.item_type, item_path(req.item), :class => "item-link" %>
   <% end %>
<% elsif req.recall? %>
   <% if req.gifter?(current_person) -%>
      <% full_sentence = "You are requesting the return of your " + item + " from " + requester %>
   <% else -%>
       <% full_sentence = gifter_non_possessive + " is requesting the return of their " + item %>
   <% end -%>
<% elsif req.in_return? %>
   <% if req.gifter?(current_person) -%>
      <% full_sentence = requester + " would like to return your " + item %>
   <% else -%>
      <% full_sentence = "Requesting return of  " + gifter + " " + item %>
   <% end -%>
<% elsif req.acknowledged? %>
   <% if req.gifter?(current_person) -%>
      <% full_sentence = "Awaiting return of your " + item + " from " +requester %>
   <% else -%>
      <% full_sentence = "You need to return " + gifter + " " + item %>
   <% end -%>
<% elsif false %>
   <% if req.gifter?(current_person) -%>
      <% full_sentence = "Awaiting return of your " + item +" from " + requester %>
   <% else -%>
      <% full_sentence = "Return the " + item + " to " + gifter%>
   <% end -%>
<% end %>

<% if dashboard -%>
  <% if req.item.is_shareage? -%>
    <%= full_sentence.html_safe %>
  <% else -%>
    <%= (person_one + " " + sentence+ " " + person_two + " " + item + sentence_ending).html_safe unless person_one.nil? && sentence.nil? if !person_one.nil? && !person_two.nil? && !sentence.nil?%>	
  <% end -%>
  
<% elsif !person_one.nil? && !person_two.nil? && !sentence.nil? && !sentence.nil? -%>
   <h2>
		<span>
			<%= person_one %>
			<%= (sentence + " "  + person_two).html_safe %> <%= item %>
		</span>
	</h2>
<% elsif !full_sentence.nil? -%>
   <h2>
		<span>
			<%= full_sentence.html_safe %>
		</span>
	</h2>
<% end -%>

app/views/shared/_latest_activity.html.erb
<!-- 
basti-todo: Latest Activity (note below is from Dan)
	
Latest Activity consists of chronological events from the NewsFeed
model that relate to the item\person in question. for the item page,
it should show the latest activity relating to the item. for the
people & request page it should show the latest activity relating to
the other person.

for someone else looking at an item page, and the Latest Activity should show
chronological events that the item has been involved in. As mentioned
above, use the NewsFeed model to generate this, not the RecentActivity
model.

when looking at a request page, and the Latest Activity should show events
relating to the other person in the transaction as well.
-->


<h2 class="default-title">Latest Activity</h2>
<ul>
	<li class="sidebar-box clearfix">
		<div class="inner-content">
			<p>
				Andrea lent a modem to <a class="positive" href="#">Terry Waters</a>
			</p>

			<div class="action clearfix">
				<ul>
					<li>3 days ago</li>
					<li><a href="#">comments(0)</a></li>
				</ul>
			</div>
		</div>
	</li>
	<li class="sidebar-box clearfix">
		<div class="inner-content">
			<p>
				Andrea borrowed a witches costume from <a class="positive" href="#">Dan Brown</a>
			</p>

			<div class="action clearfix">
				<ul>
					<li>2 weeks ago</li>
					<li><a href="#">comments(0)</a></li>
				</ul>
			</div>
		</div>
	</li>
	<li class="sidebar-box clearfix">
		<div class="inner-content">
			<p>
				Andrea started sharing a BBQ
			</p>

			<div class="action clearfix">
				<ul>
					<li>3 weeks ago</li>
					<li><a href="#">comments(0)</a></li>
				</ul>
			</div>
		</div>
	</li>
</ul>

app/views/shared/_latest_activity_person.html.haml
%div.story.clearfix
	%h2 Latest Activity
	%ul
		-feed = Array.new()

		-person.public_events.each do |event_log|
			-sentence = event_log_sentence(event_log, person, EventDisplay::RECENT_ACTIVITY_FEED)
			-time = event_log.created_at
			-feed.push({"value" => sentence, "time" => time, "log" => event_log })
		-end unless person.public_events.empty?

		-person.public_activities(current_user).each do |activity_log|
			-sentence = recent_activity_sentence(activity_log)
			-time = activity_log.created_at
			-feed.push({"value" => sentence, "time" => time, "log" => activity_log })
		-end unless person.public_activities(current_user).empty?

		-feed = feed.sort_by { |feed| feed["time"] }.last(7).reverse
		-feed.each do |sentence|
			-log = sentence["log"]
			-event = log.class.name == "EventLog" ? true : false
			%li
				
				%div.story-main
					= sentence["value"]
				
				%ul
					%li
						= "#{time_ago_in_words(sentence["time"])} ago"
					-if event
						%li
							=link_to "comments #{log.comments.count}", "#", :class => "comments-show-hide"
							/ %a.comments-show-hide{:href => "#"}
							/ 	comments("#{log.comments.count}")

			-if event
				= render :partial => '/comments/comment_box', :locals => {:object => log}
		-end unless feed.empty?

		-if feed.empty?
			%li
				%p
					This person doesn't have any activity yet

app/views/shared/_lightbox.haml
#lightbox_wrapper.hidden
  .loading
  .overlay

app/views/shared/_news_feed_emty.html.erb
<h2>Your Network Activity</h2>
<ul>
	<li class="sidebar-box clearfix">
		<div class="inner-content">
			<p>
				You are isolated from the network. <a class="trusted" href="#">Establish</a> a <a class="trusted" href="#">trusted network</a> or <a class="trusted" href="#">join</a> local <a class="trusted" href="#">villages</a> and <a class="trusted" href="#">communities</a> near you.
			</p>
		</div>
	</li>
</ul>

app/views/shared/_notification.html.erb
<!-- Handle flash messages here as they are displayed in notification -->

<% if !flash.empty? %>
	<script>
	window.notificationTitle = window.notificationTitle || "Notice";
	window.notificationMessage = window.notificationMessage || "";

	<% flash.each do |name, msg| %>
		<%
			# this will output all set flash messages and it will give each appropriate id
			# possible values include: flash-notice and flash-alert
			# (CSS rules also allow flash-info - which is not used at the moment)
		%>
		window.notificationTitle = "<%= name.capitalize %>";
		window.notificationMessage += "<%=raw escape_javascript( msg ) %><br \/>";
	<% end %>

	</script>
<% end %>

<div id="notification-overlay" ></div>

<div id="notification-box" >
	<table>
		<tr id="notification-header">
			<td>
				<span id="notification-title"> This is test</span>
				<%= image_tag 'closelabel.png', :style => "float:right;", :id => "notification-close" %>
			</td>
		</tr>
		<tr>
			<td id="notification-body">
				This is body
			</td>
		</tr>
		<tr id="notification-footer" >
			<td>
				<button id="notification-ok">OK</button>
			</td>
		</tr>
	</table>
</div>

app/views/shared/_person_network_request_actions_compact.html.erb
<%
	# compact version of available person network request actions based on user's role
	# for example it's used in dashboard.html.erb
%>

<% if req.requester?(current_user.person) %>
	<%= link_to "cancel", people_network_request_path(req.trusted_person), :method => :delete %>
<% else %>
	<%= link_to "confirm", "#", :method => :put %>
	<%= link_to "deny", "#", :method => :put %>
<% end %>

app/views/shared/_trust_status.html.haml
- viewing_my_profile = (person == current_user.person)

-unless viewing_my_profile

	-if person.requested_trusted_relationship?(current_user.person)
		= link_to "cancel trust request", network_request_path(person.requested_trusted_relationship(current_user.person)), :method => :delete

	-elsif human_network = current_user.person.trusts?(person)
		= link_to "withdraw trust", human_network_path(human_network), :method => :delete

	-elsif current_user.person.requested_trusted_relationship?(person)
		= link_to "confirm trust", confirm_network_request_path(current_user.person.requested_trusted_relationship(person)), :id => "confirm_button", :method => :put

	-else
		= link_to "trust", network_requests_path(:trusted_person_id => person), :method => :post