config/routes.rb
Sharedearthapp::Application.routes.draw do
  resources :transparency, :only => [:index] do
    collection do
      put 'accept_tr'
    end
  end

  resource :password_resets 

  match "/password_reset/:id/edit" => "password_resets#edit"
  match "/password_reset/:id/update" => "password_resets#update"

  ActiveAdmin.routes(self)

  resources :fb_friends, :only => [:index]
  get 'connect'     => "fb_friends#index"
  get 'findtheothers' => "fb_friends#index"
  get 'search_fb_friends' => "fb_friends#search_fb_friends"
  get 'search_people'     => "fb_friends#search_people"

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end

  resources :terms, :only => [:index] do
    collection do
      put 'accept_tc'
      put 'accept_pp'
      get 'principles'
    end
  end

  resources :legal_notices, :only => [:index] do
    collection do
      put 'accept_legal_notice'
      put 'accept_pp'
      get 'principles'
    end
  end

   resources :requested_invitations, :only => [:create]

  resources :comments, :only => [:create]

  resources :invitations, :except => [:destroy, :edit, :show, :new]

  get "invitations/validate"
  get "invitations/purge"
  get "invitations/preview"
  get "invitations/switch"
  get "invitations/invite"

  get "people/cancel/:id" => "people#cancel"

  get "search/index"

  resources :items do
    member do
      put "mark_as_normal"
      put "mark_as_lost"
      put "mark_as_damaged"
      put "mark_as_hidden"
      put "mark_as_unhidden"
      post "share_mine"
      post "share_mine_type"
    end
  end

  resources :people, :only => [:new, :show, :edit, :update, :index, :destroy] do
    member do
      get :confirm_email_changing
      get :please_confirm_email_changing
      get :network
      get :my_network
    end
  end

  resources :network_requests, :only => [:create, :destroy] do
    member do
      put "confirm"
      put "deny", :action => :destroy
    end
  end

  resources :human_network, :only => [ :destroy ]

  resources :item_requests, :except => [:index, :destroy, :edit], :path => "requests", :as => "requests" do
    member do
      put "accept"
      put "reject"
      put "complete"
      put "cancel"
      put "collected"
      put "recall"
      put "return"
      put "acknowledge"
      put "cancel_recall"
      put "cancel_return"
      put "returned"
      post 'new_comment'
    end
    resources :feedbacks
  end

  resources :villages do
    member do
      put 'join'
      put 'leave'
    end
  end
  resources :entities, :only => [:destroy] do
    collection do
      get 'grow'
    end
  end

  resources :users do
    member do
      get :confirm
      post :resent_activation
      get :please_activate_email
    end
  end

  resources :sessions, :only => [:new, :create]

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  match "/dashboard", :to => "pages#dashboard"
  match "/community", :to => "pages#community"
  match "/principles", :to => "terms#principles"
  match '/about' => 'pages#about'
  match '/contribute' => 'pages#contribute'
  match '/no_javascript' => 'pages#no_javascript'
  match '/collect_email' => 'pages#collect_email'

  match "/common", :to => "pages#commons"

  post "/create_trusted_network", :to => "human_network#create_trusted_networks"

  root :to => "pages#index"

  match '*a', :to => 'application#missing_route'   #Catch wrong route problem
end

app/models/village.rb
class Village < ActiveRecord::Base
  acts_as_entity
  attr_accessible :name, :description, :street, :postcode, :state, :country,:city,:uid
  validates_length_of    :name, :maximum => 50
  validates_length_of    :state, :maximum => 30
  validates_length_of    :description, :maximum => 400
  validates_presence_of  :name
  validates_presence_of  :country
  validates_presence_of  :state

  has_human_network :human_networks

  before_create :generate_key
  after_create :create_entity_for_village

  def generate_key(length=6)
    random_number = Random.rand(999999)
    self.uid = random_number
    # Ensure uniqueness of the token..
    generate_key unless Village.find_by_uid(random_number).nil?
  end

  def is_member?(entity)
    Member.village_members(self).member(entity).first
  end

  def is_admin?(entity)
    GroupAdmin.village_admins(self).member(entity).first
  end

  def is_member_or_admin?(entity)
    GroupAdmin.village_admins(self).member(entity).first || Member.village_members(self).member(entity).first
  end

  def join!(entity)
    self.add_items!(entity)
    Member.create!(:person_id => entity.id, :specific_entity => self, :entity_id => self.id)
  end

  def add_admin!(entity)
    GroupAdmin.create!(:person_id => entity.id, :specific_entity => self)
  end

  def add_items!(entity)
    worker = AddResource.new
    worker.entity_id = self.id
    worker.entity_type_id = EntityType::VILLAGE_ENTITY
    worker.items = entity.items
    ENV['ENABLE_IRON_WORKER'].nil? ? worker.run_local : worker.queue
  end

  def add_item!(item)
    ResourceNetwork.create!(:entity_id => self.id, :entity_type_id => EntityType::VILLAGE_ENTITY, :resource_id => item.id, :resource_type_id => EntityType::ITEM_ENTITY)
  end

  def remove_item!(item)
    resource = ResourceNetwork.item(item)
    resource.destroy unless resource.nil?
  end

  def leave!(entity)
    HumanNetwork.village_members(self).member(entity).each{ |n| n.delete }
    self.remove_items!(entity)
  end

  def remove_items!(entity)
    worker = RemoveResource.new
    worker.entity_id = self.id
    worker.items = entity.items
    ENV['ENABLE_IRON_WORKER'].nil? ? worker.run_local : worker.queue
  end

  def self.belongs_to_person(person)
    HumanNetwork.part_of_village(person).map(&:entity_id) - [nil]
  end
  
  def self.person_villages(person)    
    Village.where("id IN (#{belongs_to_person(person).join(',')})")
  end

  #handle_asynchronously :add_items!
  #handle_asynchronously :remove_items!

  private

  def create_entity_for_village
    Entity.create!(:specific_entity_type => "Village", :specific_entity_id => self.id)
  end
end

app/controllers/villages_controller.rb
class VillagesController < EntitiesController
  before_filter :authenticate_user!
  before_filter :find_entity, :only => [:show, :edit, :update, :destroy, :leave, :join]
  before_filter :only_admin!, :only => [:edit, :update, :destroy]
  
  def index
    @villages = Village.all
  end

  def show
    super
  end

  def new
    @village = Village.new
  end

  def create
    @village = Village.new(params[:village])
    super
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  def join
    super
  end

  def leave
    super
  end

  private

  def find_entity
    @village = Village.find_by_id(params[:id])
  end

  def only_admin!
    redirect_to(root_path, :alert => I18n.t('messages.only_admin_can_access')) and return unless @village.is_admin?(current_user.person)
  end

end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/villages/_form.html.haml
%div
	%section.modal.create-village
		%header.row
			%h1.village Create Village
			%button.close{:onclick=>"overlay()"} Close
		%div.content.row
			%form
				= form_for @village do |f|
					= render :partial => "shared/error_messages", :locals => { :model => @village }

					=f.label :name
					=f.text_field :name, :placeholder => "Name"

					=f.label :description
					=f.text_field :description, :placeholder => "Description"
				
					=f.label :street
					=f.text_field :street, :placeholder => "Street"

					=f.label :postcode
					=f.text_field :postcode, :placeholder => "Postcode"

					=f.label :state
					=f.text_field :state, :placeholder => "State"

					=f.label :country
					=country_select("village", "country")
				
					=f.submit :value => "Create Village", :class => "button"

app/views/villages/_new_popup.html.haml
%section.modal_popup
	%header.row			
		.village-header
			%h1.village-heading Create Village

		 		
	=form_for Village.new, :id=>"textarea-input",:remote=>true ,:class=>"row" do |f|

		%div.row#textarea-input

			=#render :partial => "shared/error_messages", :locals => {:model => village }
			-village.errors.full_messages.each do |m|
				.village_errors
					=m				
			
			
			=f.text_field :name, :placeholder => "Name", :class=>"village_text"
			
			=f.text_area :description, :placeholder => "Description", :class=>"village_text_large"
			
			=f.text_field :country, :placeholder => "Countrty", :class=>"village_text"
			
			=f.text_field :state, :placeholder => "State", :class=>"village_text"

			=f.text_field :city, :placeholder => "City (optional)", :class=>"village_text"
			
			=f.text_field :postcode, :placeholder => "Postcode (optional) ", :class=>"village_text"				
			=f.text_field :street, :placeholder => "Street (optional)", :class=>"village_text"
			
			

			

		
			=f.submit :value => "Create Village", :class => "button create-village-btn"
		%div.row#textarea-input

app/views/villages/create.js.erb
window.location = '<%= connect_path %>';

app/views/villages/edit.html.haml
=render "form"

app/views/villages/index.html.haml
%ul.list
	-for village in @villages
		%li
			=village.name
			=link_to 'Join', join_village_path(village)

%table
	%tr
		%th Name
		%th Description
		%th Street
		%th Postcode
		%th State
		%th Country
		%th Uid

	-for village in @villages
		%tr
			%td
				=village.name
			%td
				=village.description
			%td
				=village.street
			%td
				=village.postcode
			%td
				=village.state
			%td
				=village.country
			%td
				=village.uid
			%td
				=link_to "Show", village
			%td
				=link_to "Edit", edit_village_path(village)
			%td
				=link_to "Destroy", village, :confirm => "Are you sure?", :method => :delete

%p
	= link_to "New Village", new_village_path

app/views/villages/new.html.haml
=render "form"

app/views/villages/new.js.erb
$("#facebox .content").html('<%=escape_javascript(render :partial=> "new_popup", :locals=>{:village=> @village} ).html_safe %>');

app/views/villages/show.html.haml
%p
	%strong
		="Name: #{@village.name}"
	%strong
		="Description: #{@village.description}"
	%strong
		="Street: #{@village.street}"
	%strong
		="Country: #{@village.state}"
	%strong
		="Uid: #{@village.uid}"